### ISSUE TITLE
Fix permission error

### ISSUE THREAD

**Issue by tarolling** [tarolling/rps-bot-old#10]
Error log
```shell
/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:730
      throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
            ^

DiscordAPIError[50001]: Missing Access
    at handleErrors (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:1133:23)
    at async SequentialHandler.queueRequest (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:963:14)
    at async _REST.request (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:1278:22)
    at async TextChannel.send (/home/minecraft/multicraft/servers/server776960/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:177:15)
    at async Object.execute (/home/minecraft/multicraft/servers/server776960/commands/rps/leave.js:21:17)
    at async Timeout.<anonymous> (/home/minecraft/multicraft/servers/server776960/commands/rps/queue.js:42:13) {
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      enforce_nonce: false,
      embeds: [
        {
          title: '0 players are in the queue',
          description: '**coffeee7217** has left.',
          thumbnail: { url: 'https://cdn.discordapp.com/embed/avatars/4.png' },
          footer: {
            text: 'Powered by RPS',
            icon_url: 'https://i.imgur.com/YODnmBn.png'
          }
        }
      ],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined,
      applied_tags: undefined,
      poll: undefined
    }
  },
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/1260051499048763484/messages'
}
```

**Comment by tarolling** [comment]
this may have been a permissions and/or intents error, so i changed intents in f3068475c64a5eb7454ae8c4305bb4a9716006a0 and also changed invite perms to 274877975552. hopefully that fixes it

**Comment by tarolling** [comment]
actually i realize now that there is a guild role assignment lurking somewhere in my code, so this is still relevant
```shell
DiscordAPIError[50001]: Missing Access
    at handleErrors (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:1133:23)
    at async SequentialHandler.queueRequest (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:963:14)
    at async _REST.request (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:1278:22)
    at async GuildMemberRoleManager.add (/home/minecraft/multicraft/servers/server776960/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:131:7)
    at async Object.execute (/home/minecraft/multicraft/servers/server776960/commands/rps/ping.js:40:34)
    at async Object.execute (/home/minecraft/multicraft/servers/server776960/events/interactionCreate.js:17:13) {
  requestBody: { files: undefined, json: undefined },
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'PUT',
  url: 'https://discord.com/api/v10/guilds/938672929951076353/members/949694007481618523/roles/993619734392213566'
}
```
