### ISSUE TITLE
(bug) address invalid webhook token error

### ISSUE THREAD

**Issue by tarolling** [tarolling/rps-bot-old#83]
logs

```shell
tevimzzz joined Lobby 9
COMMAND: q by tevimzzz (1234273267729305714 - Guild: 1160336554280099880) Locale: pt-BR, msecs: 1371
tevimzzz left Lobby 9
DiscordAPIError[50027]: Invalid Webhook Token
    at handleErrors (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:1133:23)
    at async SequentialHandler.queueRequest (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:963:14)
    at async _REST.request (/home/minecraft/multicraft/servers/server776960/node_modules/@discordjs/rest/dist/index.js:1278:22)
    at async InteractionWebhook.send (/home/minecraft/multicraft/servers/server776960/node_modules/discord.js/src/structures/Webhook.js:224:15) {
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      enforce_nonce: false,
      embeds: [Array],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined,
      applied_tags: undefined,
      poll: undefined
    }
  },
  rawError: { message: 'Invalid Webhook Token', code: 50027 },
  code: 50027,
  status: 401,
  method: 'POST',
  url: 'https://discord.com/api/v10/webhooks/638351152131604521/aW50ZXJhY3Rpb246MTI2NTg2NDYyNTcwNzE1OTU3MzpId3Z2djZGWlBRcU96ME5GZ0xabDhmaTFWWklCYTNZNDNqSUtjSHpIWDZ3aVVzNEY0bE9aZ0RFTWFQakdGb00yZGRSY1k0TnU1b2pmNVZqOFVWM25yS09VNk9aQnR1WmkwcXhOZzBLczByRUpsZmVXMjJzbFFrd2s2VjU3ZEtUbg?wait=true'
}
```

**Comment by tarolling** [comment]
also unknown message error
```shell
25.07 15:03:25 [Bot] COMMAND: play by flamin_xhot (890802759517999115 - Guild: 1239264858285801593) Locale: en-US, msecs: 1772
25.07 15:03:51 [Bot] _m7nt4l_ left Lobby 9
25.07 15:03:56 [Bot] DiscordAPIError[10008]: Unknown Message
25.07 15:03:56 [Bot] at handleErrors (/node_modules/@discordjs/rest/dist/index.js:730:13)
25.07 15:03:56 [Bot] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25.07 15:03:56 [Bot] at async SequentialHandler.runRequest (/node_modules/@discordjs/rest/dist/index.js:1133:23)
25.07 15:03:56 [Bot] at async SequentialHandler.queueRequest (/node_modules/@discordjs/rest/dist/index.js:963:14)
25.07 15:03:56 [Bot] at async _REST.request (/node_modules/@discordjs/rest/dist/index.js:1278:22)
25.07 15:03:56 [Bot] at async InteractionWebhook.editMessage (/node_modules/discord.js/src/structures/Webhook.js:341:15)
25.07 15:03:56 [Bot] at async ChatInputCommandInteraction.editReply (/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:161:17) {
25.07 15:03:56 [Bot] requestBody: {
25.07 15:03:56 [Bot] files: [],
25.07 15:03:56 [Bot] json: {
25.07 15:03:56 [Bot] content: 'Challenge timed out.',
25.07 15:03:56 [Bot] tts: false,
25.07 15:03:56 [Bot] nonce: undefined,
25.07 15:03:56 [Bot] enforce_nonce: false,
25.07 15:03:56 [Bot] embeds: undefined,
25.07 15:03:56 [Bot] components: undefined,
25.07 15:03:56 [Bot] username: undefined,
25.07 15:03:56 [Bot] avatar_url: undefined,
25.07 15:03:56 [Bot] allowed_mentions: [Object],
25.07 15:03:56 [Bot] flags: 64,
25.07 15:03:56 [Bot] message_reference: undefined,
25.07 15:03:56 [Bot] attachments: undefined,
25.07 15:03:56 [Bot] sticker_ids: undefined,
25.07 15:03:56 [Bot] thread_name: undefined,
25.07 15:03:56 [Bot] applied_tags: undefined,
25.07 15:03:56 [Bot] poll: undefined
25.07 15:03:56 [Bot] }
25.07 15:03:56 [Bot] },
25.07 15:03:56 [Bot] rawError: { message: 'Unknown Message', code: 10008 },
25.07 15:03:56 [Bot] code: 10008,
25.07 15:03:56 [Bot] status: 404,
25.07 15:03:56 [Bot] method: 'PATCH',
25.07 15:03:56 [Bot] url: 'https://discord.com/api/v10/webhooks/638351152131604521/aW50ZXJhY3Rpb246MTI2NjEwODU2MDUwOTUwMTQ5MDpUNllPMVV4T3RFZE51QnpqU2NROXMwYkNlY2kzcFBsVDN3dlU1TTV3YVBIQU5XUlhqVzlja1Y5c0hNYWNOd3UyZWF2bnFhazJmeW56UU1scUMzRXFORDJOYUQyaDZ3dVJ1dHlVTTBoa3h5bDRHV3k1bjNSWTlFNTZ0c1pXN3V1MA/messages/@original'
25.07 15:03:56 [Bot] }
```

**Comment by tarolling** [comment]
anotha one
```shell
26.07 14:06:13 [Bot] COMMAND: lb by tylergameryt (1135892597852868690 - Guild: 1266435346258723018) Locale: en-GB, msecs: 1168
26.07 14:06:20 [Bot] DiscordAPIError[10008]: Unknown Message
26.07 14:06:20 [Bot] at handleErrors (/node_modules/@discordjs/rest/dist/index.js:730:13)
26.07 14:06:20 [Bot] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
26.07 14:06:20 [Bot] at async SequentialHandler.runRequest (/node_modules/@discordjs/rest/dist/index.js:1133:23)
26.07 14:06:20 [Bot] at async SequentialHandler.queueRequest (/node_modules/@discordjs/rest/dist/index.js:963:14)
26.07 14:06:20 [Bot] at async _REST.request (/node_modules/@discordjs/rest/dist/index.js:1278:22)
26.07 14:06:20 [Bot] at async InteractionWebhook.editMessage (/node_modules/discord.js/src/structures/Webhook.js:341:15)
26.07 14:06:20 [Bot] at async ChatInputCommandInteraction.editReply (/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:161:17) {
26.07 14:06:20 [Bot] requestBody: {
26.07 14:06:20 [Bot] files: [],
26.07 14:06:20 [Bot] json: {
26.07 14:06:20 [Bot] content: undefined,
26.07 14:06:20 [Bot] tts: false,
26.07 14:06:20 [Bot] nonce: undefined,
26.07 14:06:20 [Bot] enforce_nonce: false,
26.07 14:06:20 [Bot] embeds: undefined,
26.07 14:06:20 [Bot] components: [],
26.07 14:06:20 [Bot] username: undefined,
26.07 14:06:20 [Bot] avatar_url: undefined,
26.07 14:06:20 [Bot] allowed_mentions: undefined,
26.07 14:06:20 [Bot] flags: undefined,
26.07 14:06:20 [Bot] message_reference: undefined,
26.07 14:06:20 [Bot] attachments: undefined,
26.07 14:06:20 [Bot] sticker_ids: undefined,
26.07 14:06:20 [Bot] thread_name: undefined,
26.07 14:06:20 [Bot] applied_tags: undefined,
26.07 14:06:20 [Bot] poll: undefined
26.07 14:06:20 [Bot] }
26.07 14:06:20 [Bot] },
26.07 14:06:20 [Bot] rawError: { message: 'Unknown Message', code: 10008 },
26.07 14:06:20 [Bot] code: 10008,
26.07 14:06:20 [Bot] status: 404,
26.07 14:06:20 [Bot] method: 'PATCH',
26.07 14:06:20 [Bot] url: 'https://discord.com/api/v10/webhooks/638351152131604521/aW50ZXJhY3Rpb246MTI2NjQ1NjU1NDM2Mjc2OTQ5MDp1VThuWXpPT21QRlhKYjZ0U0Q5R1FLQlJKZmNSaGtOUGxtZ05neWIxN25GbEIxQzRFcE4wZXJSM2YxektxTXJJNWVWcThQZ1VXaUJHSXBXMFZ6NGQ2UzZNcWVUT1E4a1FHcndDNktDdWRFSUZjSENoc1BLT2RSbkI2REx0WHNXVg/messages/@original'
26.07 14:06:20 [Bot] }
```
